export const SET_LOGIN_STATE = "SET_LOGIN_STATE";
export const SET_TOKEN = "SET_TOKEN";
export const SET_LOGIN_ADDRESS = "SET_LOGIN_ADDRESS";
export const SET_LOGIN = "SET_LOGIN";
export const SET_LOGIN_LOADING = "SET_LOGIN_LOADING";
