export const SET_USER_DATA = "SET_USER_DATA";
export const SET_USER_BALANCE = "SET_USER_BALANCE";
export const SET_ACCOUNT_DETAILS = "SET_ACCOUNT_DETAILS";
export const SET_USER_SIGNATURE = "SET_USER_SIGNATURE";
export const SET_USER_MESSAGE = "SET_USER_MESSAGE";
export const RESET_ACCOOUNT_DETAILS = "RESET_ACCOOUNT_DETAILS";
