export const SET_WEB3_INSTANCE = "SET_WEB3_INSTANCE";
export const SET_CHAIN_ID = "SET_CHAIN_ID";
export const SET_HAS_METAMASK = "SET_HAS_METAMASK";
export const SET_PROVIDER = "SET_PROVIDER";
export const SET_SHARE_VISIBILITY = "SET_SHARE_VISIBILITY";
export const SET_THEME = "SET_THEME";
export const SET_CONFIRM_DATA = "SET_CONFIRM_DATA";
